version: '3.3'

networks:
  clap:

services:
  clap-gateway-api:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    volumes:
      - "..:/repo"
    networks:
      - clap
